### ISSUE TITLE
i remember asking

### ISSUE THREAD

**Issue by itsmebombie** [SpeckyYT/DCMPLR#1]
custom file path :t_:

**Comment by SpeckyYT** [comment]
custom file path to what?

**Comment by itsmebombie** [comment]
for cclevels dat thing

**Comment by SpeckyYT** [comment]
you can easily change line 12 in main.rs to make it take a different file

**Comment by itsmebombie** [comment]
yes i know but make it as a command option

**Comment by SpeckyYT** [comment]
> yes i know but make it as a command option

there isn't even clap yet 💀💀💀💀💀

**Comment by itsmebombie** [comment]
i remember asking
